org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

ic2r_version=2.10.39-ex120
ic2r_version_range=[2.10.39-ex120,)
ic2r_jar_name=ic2-forge-2.10.39-ex120.jar

buildcraft_version=7.99.24.9
buildcraft_version_range=[7.99.24.9,)
buildcraft_artifact_version=7.99.24.9-1.20.1-2026-03-09T02-31-28+0800-all
buildcraft_jar_name=buildcraft-7.99.24.9-1.20.1-2026-03-09T02-31-28+0800-all.jar

jei_version=15.20.0.130
jade_version=11.13.2+forge
jade_version_id=LecuGude

mod_id=advanced_solar_panels_refactored
mod_name=Advanced Solar Panels: Refactored
mod_license=All Rights Reserved
mod_version=0.4.0-beta.3
mod_group_id=com.refactoredsolarpanels
mod_authors=catl
mod_description=An IndustrialCraft 2: Refactored addon that adds higher tier solar generators with optional JEI and Jade integration.
